### ISSUE TITLE
[REQ] Use Case - Upload de Vídeos

### ISSUE THREAD

**Issue by CauBitten** [CauBitten/SaraVideo#10]
#### Atores: 

- #6 
- #14 
- #34 

#### **Fluxo Básico:**

1. O usuário aperta no botão de upload.
2. O usuário anexa o(s) vídeo(s).
3. O usuário faz upload dos vídeos anexados.
4. O usuário recebe um popup de upload concluido.

#### **1° Fluxo Alternativo:** 

1. O vídeo é muito grande para realizar upload.

#### **2° Fluxo Alternativo:** 

1. O upload falha.

#### **3° Fluxo Alternativo:** 

1. Arquivo de upload incompatível.

**Comment by higorm7** [comment]
É interessante verificar a necessidade de uma limitação para tamanhos enormes de vídeo e quantidade de uploads de um usuário
