### ISSUE TITLE
[REQ] Use Case - Informações do Site

### ISSUE THREAD

**Issue by CauBitten** [CauBitten/SaraVideo#17]
#### Atores: 

- #3 
- #6 
- #26 
- #31 

#### **Fluxo Básico:**

1. Usuário lê na tela as informações básicas. 
2. Usuário scroll para baixo.
3. Usuário lê formas de contactar a empresa do site.

#### **1° Fluxo Alternativo:**

1. Usuário vai direto ao #7 

#### **2° Fluxo Alternativo:**

1. Usuário vai direto ao #13

**Comment by anapaulafurtado** [comment]
- Numerar os passos do fluxo principal e dos alternativos
- Incluir resultados esperados
- Rastreabilidade para a História do usuário relacionada
