### ISSUE TITLE
[REQ] Use Case - Sign In

### ISSUE THREAD

**Issue by CauBitten** [CauBitten/SaraVideo#7]
#### Atores: 

- #3 
- #4 
- #25 
- #26 
- #31 

#### **Fluxo Básico:**

1. O usuário digita seu e-mail.
2. O usuário digita sua senha.
3. O sistema verifica se as credenciais informadas são válidas.
4. O sistema concede acesso ao usuário.

#### **1° Fluxo Alternativo:**

1. Se as credenciais forem inválidas.
2. O sistema exibe uma mensagem de erro.

#### **2° Fluxo Alternativo:**

1. O usuário esquece sua senha.
2. Solicita a recuperação da mesma.

**Comment by LucasRMacielP** [comment]
O usuário não digitará seu CPF, pois não foi cadastrado, digitará seu e-mail.
